CREATE TABLE if not exists BOOK (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
TITLE TEXT NOT NULL,
AUTHOR TEXT NOT NULL,
YEAR_OF_PUBLICATION INTEGER NOT NULL,
PUBLISHER TEXT NOT NULL,
SUBJECT TEXT,
AUTHOR_ID INTEGER,
PUBLISHER_ID INTEGER,
FOREIGN KEY(AUTHOR_ID) REFERENCES AUTHOR(id),
FOREIGN KEY(PUBLISHER_ID) REFERENCES PUBLISHER(id)
);

allBooks:
SELECT *
FROM BOOK;

CREATE TABLE if not exists AUTHOR (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 FIRSTNAME TEXT NOT NULL,
 SURNAME TEXT NOT NULL
);


CREATE TABLE if not exists PUBLISHER (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 NAME TEXT NOT NULL
 );


--drop table LECTURER
--drop table FACULTY